var files_dup =
[
    [ "atlas.h", "atlas_8h.html", "atlas_8h" ],
    [ "atlas_type.h", "atlas__type_8h.html", "atlas__type_8h" ],
    [ "batch.h", "batch_8h.html", "batch_8h" ],
    [ "blend_mode.h", "blend__mode_8h.html", "blend__mode_8h" ],
    [ "boolean.h", "boolean_8h.html", "boolean_8h" ],
    [ "button_state.h", "button__state_8h.html", "button__state_8h" ],
    [ "cursor.h", "cursor_8h.html", "cursor_8h" ],
    [ "cursor_mode.h", "cursor__mode_8h.html", "cursor__mode_8h" ],
    [ "cursor_shape.h", "cursor__shape_8h.html", "cursor__shape_8h" ],
    [ "debug.h", "debug_8h.html", "debug_8h" ],
    [ "desktop_callback.h", "desktop__callback_8h.html", "desktop__callback_8h" ],
    [ "detail_flag.h", "detail__flag_8h.html", "detail__flag_8h" ],
    [ "detail_mode.h", "detail__mode_8h.html", "detail__mode_8h" ],
    [ "error_code.h", "error__code_8h.html", "error__code_8h" ],
    [ "events.h", "events_8h.html", "events_8h" ],
    [ "filter_mode.h", "filter__mode_8h.html", "filter__mode_8h" ],
    [ "heap.h", "heap_8h.html", "heap_8h" ],
    [ "image.h", "image_8h.html", "image_8h" ],
    [ "keyboard_key.h", "keyboard__key_8h.html", "keyboard__key_8h" ],
    [ "keyboard_mod.h", "keyboard__mod_8h.html", "keyboard__mod_8h" ],
    [ "monitor.h", "monitor_8h.html", "monitor_8h" ],
    [ "mouse_button.h", "mouse__button_8h.html", "mouse__button_8h" ],
    [ "palette.h", "palette_8h.html", "palette_8h" ],
    [ "panel.h", "panel_8h.html", "panel_8h" ],
    [ "system.h", "system_8h.html", "system_8h" ],
    [ "texture.h", "texture_8h.html", "texture_8h" ],
    [ "time.h", "time_8h.html", "time_8h" ],
    [ "tuic.h", "tuic_8h.html", null ],
    [ "types.h", "types_8h.html", "types_8h" ],
    [ "window.h", "window_8h.html", "window_8h" ]
];