#include <TUIC/tuic.h>
#include <string>
#include <catch2/catch.hpp>
#define TO_STRING(value) #value

TEST_CASE("tuiBoxPartToString") {
    REQUIRE(std::string(tuiBoxPartToString(TUI_BOX_PART_LEFT_SIDE)) == std::string(TO_STRING(TUI_BOX_PART_LEFT_SIDE)));
    REQUIRE(std::string(tuiBoxPartToString(TUI_BOX_PART_TOP_LEFT_CORNER)) == std::string(TO_STRING(TUI_BOX_PART_TOP_LEFT_CORNER)));
    REQUIRE(std::string(tuiBoxPartToString(TUI_BOX_PART_TOP_SIDE)) == std::string(TO_STRING(TUI_BOX_PART_TOP_SIDE)));
    REQUIRE(std::string(tuiBoxPartToString(TUI_BOX_PART_TOP_RIGHT_CORNER)) == std::string(TO_STRING(TUI_BOX_PART_TOP_RIGHT_CORNER)));
    REQUIRE(std::string(tuiBoxPartToString(TUI_BOX_PART_RIGHT_SIDE)) == std::string(TO_STRING(TUI_BOX_PART_RIGHT_SIDE)));
    REQUIRE(std::string(tuiBoxPartToString(TUI_BOX_PART_BOTTOM_RIGHT_CORNER)) == std::string(TO_STRING(TUI_BOX_PART_BOTTOM_RIGHT_CORNER)));
    REQUIRE(std::string(tuiBoxPartToString(TUI_BOX_PART_BOTTOM_SIDE)) == std::string(TO_STRING(TUI_BOX_PART_BOTTOM_SIDE)));
    REQUIRE(std::string(tuiBoxPartToString(TUI_BOX_PART_BOTTOM_LEFT_CORNER)) == std::string(TO_STRING(TUI_BOX_PART_BOTTOM_LEFT_CORNER)));
}

TEST_CASE("tuiStringToBoxPart") {
    REQUIRE(tuiStringToBoxPart(TO_STRING(TUI_BOX_PART_LEFT_SIDE)) == TUI_BOX_PART_LEFT_SIDE);
    REQUIRE(tuiStringToBoxPart(TO_STRING(TUI_BOX_PART_TOP_LEFT_CORNER)) == TUI_BOX_PART_TOP_LEFT_CORNER);
    REQUIRE(tuiStringToBoxPart(TO_STRING(TUI_BOX_PART_TOP_SIDE)) == TUI_BOX_PART_TOP_SIDE);
    REQUIRE(tuiStringToBoxPart(TO_STRING(TUI_BOX_PART_TOP_RIGHT_CORNER)) == TUI_BOX_PART_TOP_RIGHT_CORNER);
    REQUIRE(tuiStringToBoxPart(TO_STRING(TUI_BOX_PART_RIGHT_SIDE)) == TUI_BOX_PART_RIGHT_SIDE);
    REQUIRE(tuiStringToBoxPart(TO_STRING(TUI_BOX_PART_BOTTOM_RIGHT_CORNER)) == TUI_BOX_PART_BOTTOM_RIGHT_CORNER);
    REQUIRE(tuiStringToBoxPart(TO_STRING(TUI_BOX_PART_BOTTOM_SIDE)) == TUI_BOX_PART_BOTTOM_SIDE);
    REQUIRE(tuiStringToBoxPart(TO_STRING(TUI_BOX_PART_BOTTOM_LEFT_CORNER)) == TUI_BOX_PART_BOTTOM_LEFT_CORNER);
}