#include <TUIC/tuic.h>
#include <string>
#include <catch2/catch.hpp>
#define TO_STRING(value) #value

TEST_CASE("tuiDetailModeToString") {
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G0_C8NBG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G0_C8NBG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G0_C24NBG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G0_C24NBG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G0_C32NBG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G0_C32NBG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C0_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C0_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C4_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C4_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C8_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C8_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C8NBG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C8NBG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C8NFG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C8NFG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C24_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C24_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C24NBG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C24NBG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C24NFG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C24NFG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C32_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C32_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C32NBG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C32NBG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C32NFG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C32NFG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C0_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C0_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C4_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C4_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C8_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C8_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C8NBG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C8NBG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C8NFG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C8NFG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C24_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C24_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C24NBG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C24NBG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C24NFG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C24NFG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C32_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C32_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C32NBG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C32NBG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C32NFG_FULL)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C32NFG_FULL)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G0_C8NBG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G0_C8NBG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G0_C24NBG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G0_C24NBG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G0_C32NBG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G0_C32NBG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C0_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C0_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C4_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C4_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C8_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C8_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C8NBG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C8NBG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C8NFG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C8NFG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C24_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C24_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C24NBG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C24NBG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C24NFG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C24NFG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C32_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C32_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C32NBG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C32NBG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C32NFG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C32NFG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C0_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C0_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C4_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C4_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C8_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C8_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C8NBG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C8NBG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C8NFG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C8NFG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C24_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C24_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C24NBG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C24NBG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C24NFG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C24NFG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C32_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C32_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C32NBG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C32NBG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C32NFG_SPARSE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C32NFG_SPARSE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G0_C8NBG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G0_C8NBG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G0_C24NBG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G0_C24NBG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G0_C32NBG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G0_C32NBG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C0_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C0_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C4_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C4_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C8_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C8_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C8NBG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C8NBG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C8NFG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C8NFG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C24_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C24_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C24NBG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C24NBG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C24NFG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C24NFG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C32_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C32_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C32NBG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C32NBG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G8_C32NFG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G8_C32NFG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C0_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C0_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C4_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C4_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C8_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C8_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C8NBG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C8NBG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C8NFG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C8NFG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C24_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C24_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C24NBG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C24NBG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C24NFG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C24NFG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C32_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C32_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C32NBG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C32NBG_FREE)));
    REQUIRE(std::string(tuiDetailModeToString(TUI_DETAIL_MODE_G16_C32NFG_FREE)) == std::string(TO_STRING(TUI_DETAIL_MODE_G16_C32NFG_FREE)));
}

TEST_CASE("tuiStringToDetailMode") {
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C0_FULL)) == TUI_DETAIL_MODE_G8_C0_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C4_FULL)) == TUI_DETAIL_MODE_G8_C4_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C8_FULL)) == TUI_DETAIL_MODE_G8_C8_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C8NBG_FULL)) == TUI_DETAIL_MODE_G8_C8NBG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C8NFG_FULL)) == TUI_DETAIL_MODE_G8_C8NFG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C24_FULL)) == TUI_DETAIL_MODE_G8_C24_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C24NBG_FULL)) == TUI_DETAIL_MODE_G8_C24NBG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C24NFG_FULL)) == TUI_DETAIL_MODE_G8_C24NFG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C32_FULL)) == TUI_DETAIL_MODE_G8_C32_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C32NBG_FULL)) == TUI_DETAIL_MODE_G8_C32NBG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C32NFG_FULL)) == TUI_DETAIL_MODE_G8_C32NFG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C0_FULL)) == TUI_DETAIL_MODE_G16_C0_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C4_FULL)) == TUI_DETAIL_MODE_G16_C4_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C8_FULL)) == TUI_DETAIL_MODE_G16_C8_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C8NBG_FULL)) == TUI_DETAIL_MODE_G16_C8NBG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C8NFG_FULL)) == TUI_DETAIL_MODE_G16_C8NFG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C24_FULL)) == TUI_DETAIL_MODE_G16_C24_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C24NBG_FULL)) == TUI_DETAIL_MODE_G16_C24NBG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C24NFG_FULL)) == TUI_DETAIL_MODE_G16_C24NFG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C32_FULL)) == TUI_DETAIL_MODE_G16_C32_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C32NBG_FULL)) == TUI_DETAIL_MODE_G16_C32NBG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C32NFG_FULL)) == TUI_DETAIL_MODE_G16_C32NFG_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C0_SPARSE)) == TUI_DETAIL_MODE_G8_C0_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C4_SPARSE)) == TUI_DETAIL_MODE_G8_C4_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C8_SPARSE)) == TUI_DETAIL_MODE_G8_C8_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C8NBG_SPARSE)) == TUI_DETAIL_MODE_G8_C8NBG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C8NFG_SPARSE)) == TUI_DETAIL_MODE_G8_C8NFG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C24_SPARSE)) == TUI_DETAIL_MODE_G8_C24_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C24NBG_SPARSE)) == TUI_DETAIL_MODE_G8_C24NBG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C24NFG_SPARSE)) == TUI_DETAIL_MODE_G8_C24NFG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C32_SPARSE)) == TUI_DETAIL_MODE_G8_C32_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C32NBG_SPARSE)) == TUI_DETAIL_MODE_G8_C32NBG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C32NFG_SPARSE)) == TUI_DETAIL_MODE_G8_C32NFG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C0_SPARSE)) == TUI_DETAIL_MODE_G16_C0_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C4_SPARSE)) == TUI_DETAIL_MODE_G16_C4_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C8_SPARSE)) == TUI_DETAIL_MODE_G16_C8_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C8NBG_SPARSE)) == TUI_DETAIL_MODE_G16_C8NBG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C8NFG_SPARSE)) == TUI_DETAIL_MODE_G16_C8NFG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C24_SPARSE)) == TUI_DETAIL_MODE_G16_C24_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C24NBG_SPARSE)) == TUI_DETAIL_MODE_G16_C24NBG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C24NFG_SPARSE)) == TUI_DETAIL_MODE_G16_C24NFG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C32_SPARSE)) == TUI_DETAIL_MODE_G16_C32_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C32NBG_SPARSE)) == TUI_DETAIL_MODE_G16_C32NBG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C32NFG_SPARSE)) == TUI_DETAIL_MODE_G16_C32NFG_SPARSE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C0_FULL)) == TUI_DETAIL_MODE_G8_C0_FULL);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C4_FREE)) == TUI_DETAIL_MODE_G8_C4_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C8_FREE)) == TUI_DETAIL_MODE_G8_C8_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C8NBG_FREE)) == TUI_DETAIL_MODE_G8_C8NBG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C8NFG_FREE)) == TUI_DETAIL_MODE_G8_C8NFG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C24_FREE)) == TUI_DETAIL_MODE_G8_C24_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C24NBG_FREE)) == TUI_DETAIL_MODE_G8_C24NBG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C24NFG_FREE)) == TUI_DETAIL_MODE_G8_C24NFG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C32_FREE)) == TUI_DETAIL_MODE_G8_C32_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C32NBG_FREE)) == TUI_DETAIL_MODE_G8_C32NBG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G8_C32NFG_FREE)) == TUI_DETAIL_MODE_G8_C32NFG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C0_FREE)) == TUI_DETAIL_MODE_G16_C0_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C4_FREE)) == TUI_DETAIL_MODE_G16_C4_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C8_FREE)) == TUI_DETAIL_MODE_G16_C8_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C8NBG_FREE)) == TUI_DETAIL_MODE_G16_C8NBG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C8NFG_FREE)) == TUI_DETAIL_MODE_G16_C8NFG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C24_FREE)) == TUI_DETAIL_MODE_G16_C24_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C24NBG_FREE)) == TUI_DETAIL_MODE_G16_C24NBG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C24NFG_FREE)) == TUI_DETAIL_MODE_G16_C24NFG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C32_FREE)) == TUI_DETAIL_MODE_G16_C32_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C32NBG_FREE)) == TUI_DETAIL_MODE_G16_C32NBG_FREE);
    REQUIRE(tuiStringToDetailMode(TO_STRING(TUI_DETAIL_MODE_G16_C32NFG_FREE)) == TUI_DETAIL_MODE_G16_C32NFG_FREE);
}

TEST_CASE("tuiDetailGetGlyphFlag") {
    REQUIRE(tuiDetailGetGlyphFlag(TUI_DETAIL_MODE_G8_C0_FULL) == TUI_DETAIL_FLAG_GLYPH_8);
    REQUIRE(tuiDetailGetGlyphFlag(TUI_DETAIL_MODE_G16_C0_FULL) == TUI_DETAIL_FLAG_GLYPH_16);
}

TEST_CASE("tuiDetailGetColorFlag") {
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C0_FULL) == TUI_DETAIL_FLAG_COLOR_0);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C4_FULL) == TUI_DETAIL_FLAG_COLOR_4);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C8_FULL) == TUI_DETAIL_FLAG_COLOR_8);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C8NBG_FULL) == TUI_DETAIL_FLAG_COLOR_8NBG);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C8NFG_FULL) == TUI_DETAIL_FLAG_COLOR_8NFG);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C24_FULL) == TUI_DETAIL_FLAG_COLOR_24);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C24NBG_FULL) == TUI_DETAIL_FLAG_COLOR_24NBG);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C24NFG_FULL) == TUI_DETAIL_FLAG_COLOR_24NFG);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C32_FULL) == TUI_DETAIL_FLAG_COLOR_32);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C32NBG_FULL) == TUI_DETAIL_FLAG_COLOR_32NBG);
    REQUIRE(tuiDetailGetColorFlag(TUI_DETAIL_MODE_G8_C32NFG_FULL) == TUI_DETAIL_FLAG_COLOR_32NFG);
}

TEST_CASE("tuiDetailGetLayoutFlag") {
    REQUIRE(tuiDetailGetLayoutFlag(TUI_DETAIL_MODE_G8_C0_FULL) == TUI_DETAIL_FLAG_LAYOUT_FULL);
    REQUIRE(tuiDetailGetLayoutFlag(TUI_DETAIL_MODE_G8_C0_SPARSE) == TUI_DETAIL_FLAG_LAYOUT_SPARSE);
    REQUIRE(tuiDetailGetLayoutFlag(TUI_DETAIL_MODE_G8_C0_FREE) == TUI_DETAIL_FLAG_LAYOUT_FREE);
}

TEST_CASE("tuiDetailModeIsValid") {
    SECTION("Detail modes should all return true") {
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C0_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C4_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C8_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C8NBG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C8NFG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C24_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C24NBG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C24NFG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C32_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C32NBG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C32NFG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C0_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C4_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C8_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C8NBG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C8NFG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C24_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C24NBG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C24NFG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C32_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C32NBG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C32NFG_FULL) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C0_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C4_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C8_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C8NBG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C8NFG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C24_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C24NBG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C24NFG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C32_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C32NBG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C32NFG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C0_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C4_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C8_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C8NBG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C8NFG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C24_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C24NBG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C24NFG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C32_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C32NBG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C32NFG_SPARSE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C0_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C4_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C8_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C8NBG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C8NFG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C24_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C24NBG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C24NFG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C32_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C32NBG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G8_C32NFG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C0_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C4_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C8_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C8NBG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C8NFG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C24_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C24NBG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C24NFG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C32_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C32NBG_FREE) == TUI_TRUE);
        REQUIRE(tuiDetailIsValid(TUI_DETAIL_MODE_G16_C32NFG_FREE) == TUI_TRUE);
    }
    SECTION("Solo flags should return false.") {
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_GLYPH_8) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_GLYPH_16) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_0) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_4) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_8) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_8NBG) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_8NFG) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_24) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_24NBG) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_24NFG) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_32) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_32NBG) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_COLOR_32NFG) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_LAYOUT_FULL) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_LAYOUT_SPARSE) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)TUI_DETAIL_FLAG_LAYOUT_FREE) == TUI_FALSE);
    }
    SECTION("Too many flags of one type should return false.") {
        REQUIRE(tuiDetailIsValid((TuiDetailMode)(TUI_DETAIL_MODE_G16_C32NFG_SPARSE | TUI_DETAIL_FLAG_LAYOUT_FULL)) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)(TUI_DETAIL_MODE_G16_C32NFG_SPARSE | TUI_DETAIL_FLAG_COLOR_0)) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)(TUI_DETAIL_MODE_G16_C32NFG_SPARSE | TUI_DETAIL_FLAG_GLYPH_8)) == TUI_FALSE);
    }
    SECTION("Flags of only to kinds should return false.") {
        REQUIRE(tuiDetailIsValid((TuiDetailMode)(TUI_DETAIL_FLAG_COLOR_0 | TUI_DETAIL_FLAG_GLYPH_8)) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)(TUI_DETAIL_FLAG_COLOR_0 | TUI_DETAIL_FLAG_LAYOUT_SPARSE)) == TUI_FALSE);
        REQUIRE(tuiDetailIsValid((TuiDetailMode)(TUI_DETAIL_FLAG_LAYOUT_SPARSE | TUI_DETAIL_FLAG_GLYPH_8)) == TUI_FALSE);
    }
}